#!/usr/bin/env bash
# github_clone.sh — clone curated GitHub repositories with royalty/dynasty/genealogy
# data into data/raw/github/. Idempotent: skips repos already cloned.
#
# Usage:
#   bash scripts/fetchers/github_clone.sh
#
# Skips repos > MAX_SIZE_KB (default 500MB).
# Parallelism: 4 (matches `xargs -P 4`).
#
# Re-discovery:
#   The repo list below was generated by scouting the GitHub search and code-search
#   APIs (see scripts/fetchers/github_search.sh for the underlying query loop).
#   To refresh, re-run the search script and re-curate.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/data/raw/github"
MAX_SIZE_KB="${MAX_SIZE_KB:-512000}"   # 500 MB
PARALLEL="${PARALLEL:-4}"

mkdir -p "$OUT"

# Curated repo list. Format: owner/name
REPOS=(
  # === Real-world royal / monarchy data ===
  bertob/dynasty                                  # data/british-monarchs.csv + viz
  AfraHussaindeen/SrilankanMonarchsSE             # Sri Lankan monarchs corpus
  AkLabx/TimelineHistory                          # Indian dynasties + ruler timelines
  english8192/sandbox                             # medieval-islamic-dynasties, chinese-dynasties JSON
  yomoginna/EmbedNewConcept-20260305              # Wiki-derived ruler/dynasty page dumps
  freetalk-fun/freetalk-dictionary-v1             # words/dynasties.json, kings.json, corulers.json
  changhongzi/BNC_COCA_EN2CN                      # data/royals.json, dynasties.json, rulers.json
  fornevercollective/ancestory                    # rulers.json
  matypist/RomanEmperorsScraper                   # Roman emperor family trees
  alicetinkaya76/islamic-civilization-atlas       # 186 Islamic dynasties 632-1924 CE
  nbremer/royalconstellations                     # 1000 yrs European royal families
  mzemel/monarchs                                 # European monarchs timeline d3
  STaTbS21D/Book_of_the_Dead_Sources              # Egyptian 21st Dynasty
  dhmontgomery/personal-work                      # uk_monarchs.csv
  jstrickler/20240122mastering                    # english_monarchs.csv
  ameensol/iran-constitutional-monarchy           # Iran monarchy
  caomengge/Song-Dynasty-Paintings-Database       # Song Dynasty paintings (China)
  Linking-ai/ctm_bench                            # Benchmark: Chinese Dynasties temporal data

  # === Billionaires / wealthy families ===
  jesseokeya/Forbes400                            # Forbes 400 JSON API
  komed3/rtb-api                                  # Forbes real-time billionaires API
  komed3/rtb                                      # Real-time billionaires tracker data
  jhnwr/billionaires-scraper                      # Billionaires scraper
  richard512/Little-Big-Data                      # top1000billionaires.csv + misc
  jsoma/fuzzy_pandas                              # forbes-china + bloomberg-billionaires.csv

  # === World leaders / speeches / states ===
  stdlib-js/datasets-sotu                         # SOTU speeches (US presidents)
  lirondos/discursos-de-navidad                   # Spanish head-of-state Xmas speeches 1937-2020
  Seshat-Global-History-Databank/cliopatria       # Worldwide polities geospatial

  # === Misc data + reference ===
  JalonY/CorporateGenealogy                       # Chinese enterprise family tree
  arbre-app/public-gedcoms                        # Curated public GEDCOMs list
  vincentarelbundock/Rdatasets                    # R datasets (Wheat.monarchs etc)
  Maxoud99/tabfact                                # TabFact: shortest-reigning monarchs etc
  ShantanilBagchi/DataCamp                        # SQL/leaders/monarchs.csv
  Digital-Methods-HASS/AU681035_Sejersen_Karoline # academic Danish monarchs
  Digital-Methods-HASS/AU736876_Damborg_Michal    # academic Danish monarchs
  Digital-Methods-HASS/au593509_Eithz_Mathias     # academic Danish monarchs
  Digital-Methods-HASS/au754371_Lambaek_Julie_exam # academic Danish monarchs
  Digital-Methods-HASS/CultDat_LauraWPaaby        # academic Danish monarchs
  kept-io/r-datasets                              # SQL of Rdatasets

  # === Skipped intentionally (parsers/libraries with no data) ===
  # tmcw/gedcom, FamilySearch/gedcomx, gramps-project/gramps, fisharebest/webtrees,
  # liberu-genealogy/*, T-F-S/genealogytree, etc.
  # === Skipped: too large or unrelated CK3 mods ===
  # most CK3 mod repos are fictional (ATLA / GoT / sci-fi / fantasy) and 100s of MB.
)

echo "[github_clone] target dir: $OUT"
echo "[github_clone] $(echo "${REPOS[@]}" | wc -w | tr -d ' ') repos to consider"

clone_one() {
  local repo="$1"
  local name="${repo##*/}"
  local dir="$OUT/$name"
  if [[ -d "$dir/.git" ]]; then
    echo "  [skip] $repo (already cloned)"
    return 0
  fi
  # Pre-check size
  local size_kb
  size_kb=$(gh api "repos/$repo" --jq '.size' 2>/dev/null || echo 999999999)
  if (( size_kb > MAX_SIZE_KB )); then
    echo "  [skip] $repo (size ${size_kb}KB > ${MAX_SIZE_KB}KB)"
    return 0
  fi
  echo "  [clone] $repo  (size ${size_kb}KB)"
  if ! git clone --depth 1 --quiet "https://github.com/${repo}.git" "$dir" 2>/dev/null; then
    echo "  [fail]  $repo"
    rm -rf "$dir"
    return 0
  fi
  echo "  [done]  $repo -> $dir"
}

export -f clone_one
export OUT MAX_SIZE_KB

printf '%s\n' "${REPOS[@]}" | xargs -n1 -P "$PARALLEL" -I{} bash -c 'clone_one "$@"' _ {}

echo "[github_clone] complete"
ls -1 "$OUT" | head -100
